version: '3.5'
services:
  proxy:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    container_name: proxy
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/cert
    cpus: 1
    mem_reservation: 128M
    mem_limit: 1024M
    restart: always

  dummy:
    image: nginx:alpine
    container_name: dummy